// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb217G3IN8M_hPl2KX8ABnNRg5w6cqTt0',
    appId: '1:939364014001:web:07961bbb02aaae1cd40f90',
    messagingSenderId: '939364014001',
    projectId: 'cloud-kitchen-app-f0852',
    authDomain: 'cloud-kitchen-app-f0852.firebaseapp.com',
    storageBucket: 'cloud-kitchen-app-f0852.firebasestorage.app',
    measurementId: 'G-93FHNRSK83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF-wscUcduUcu77RolyZIkESlvYmRSG98',
    appId: '1:939364014001:android:c1fd914954736112d40f90',
    messagingSenderId: '939364014001',
    projectId: 'cloud-kitchen-app-f0852',
    storageBucket: 'cloud-kitchen-app-f0852.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTK-3r9XxxsqNnSQ2GeLztfreZJzXqhkI',
    appId: '1:939364014001:ios:e7e829bb8e309873d40f90',
    messagingSenderId: '939364014001',
    projectId: 'cloud-kitchen-app-f0852',
    storageBucket: 'cloud-kitchen-app-f0852.firebasestorage.app',
    iosBundleId: 'com.example.cloudKitchenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTK-3r9XxxsqNnSQ2GeLztfreZJzXqhkI',
    appId: '1:939364014001:ios:e7e829bb8e309873d40f90',
    messagingSenderId: '939364014001',
    projectId: 'cloud-kitchen-app-f0852',
    storageBucket: 'cloud-kitchen-app-f0852.firebasestorage.app',
    iosBundleId: 'com.example.cloudKitchenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb217G3IN8M_hPl2KX8ABnNRg5w6cqTt0',
    appId: '1:939364014001:web:24f80cbea59b8c4cd40f90',
    messagingSenderId: '939364014001',
    projectId: 'cloud-kitchen-app-f0852',
    authDomain: 'cloud-kitchen-app-f0852.firebaseapp.com',
    storageBucket: 'cloud-kitchen-app-f0852.firebasestorage.app',
    measurementId: 'G-WDYW3XGH13',
  );
}
